---
- name: Hide desktop widgets
  community.general.osx_defaults:
    domain: com.apple.WindowManager
    key: StandardHideWidgets
    type: int
    value: 1
  notify: Restart WindowManager

- name: Disable click wallpaper to reveal desktop
  community.general.osx_defaults:
    domain: com.apple.WindowManager
    key: EnableStandardClickToShowDesktop
    type: bool
    value: false
  notify: Restart WindowManager
