---
# .ansible-lint configuration

skip_list:
  - package-latest # Completely silence the "Package installs should not use latest" warning
  - latest # Completely silence the "Result of the command may vary on subsequent runs." warning
