---
- hosts: localhost
  gather_facts: true
  vars_files:
    - "{{ ansible_facts.env.HOME }}/extra_vars.yml"
  tasks:
    - name: Include roles
      include_role:
        name: "{{ role }}"
      loop: "{{ selected_roles }}"
      loop_control:
        loop_var: role
