---
- hosts: localhost
  gather_facts: true
  vars_files:
    - ~/extra_vars.yml
  tasks:
    - name: Include roles
      include_role:
        name: "{{ role }}"
      loop: "{{ selected_roles }}"
      loop_control:
        loop_var: role

  handlers:
    - name: open security settings
      command: >
        open "x-apple.systempreferences:com.apple.preference.security"
