---
- name: Setup workstation
  hosts: localhost
  gather_facts: true
  vars_files:
    - ~/extra_vars.yml
  collections:
    - community.general
  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop: "{{ selected_roles }}"
      loop_control:
        loop_var: role

  handlers:
    - name: open security settings
      ansible.builtin.command: >
        open "x-apple.systempreferences:com.apple.preference.security"
