onboarding = false

[theme]
name = "terminal"
auto_switch = false

[theme.custom]
accent = "#f4a261"
panel_bg = "#192330"
sidebar_bg = "#131a24"
active_row_bg = "#212e3f"
selection_bg = "#2b3b51"
surface0 = "#29394f"
surface1 = "#39506d"
surface_dim = "#161d29"
overlay0 = "#719cd6"
overlay1 = "#719cd6"
text = "#cdcecf"
subtext0 = "#aeafb0"
mauve = "#9d79d6"
green = "#81b29a"
yellow = "#dbc074"
red = "#c94f6d"
blue = "#719cd6"
teal = "#63cdcf"
peach = "#f4a261"

[keys]
prefix = "ctrl+a"
new_tab = "prefix+c"
split_horizontal = "prefix+x"
split_vertical = "prefix+s"
close_pane = "prefix+d"
edit_scrollback = "prefix+]"
new_worktree = ""
new_workspace = "prefix+z"
zoom = ["prefix+shift+z", "ctrl+/"]
rename_workspace = "prefix+e"
focus_pane_left = ["prefix+h", "ctrl+alt+h"]
focus_pane_down = ["prefix+j", "ctrl+alt+j"]
focus_pane_up = ["prefix+k", "ctrl+alt+k"]
focus_pane_right = ["prefix+l", "ctrl+alt+l"]
next_workspace = "prefix+shift+j"
previous_workspace = "prefix+shift+k"

[ui]
status_indicators = "symbols"

[ui.toast]
delivery = "off"

[ui.toast.clipboard]
enabled = false
