---
- name: Ensure screenshots directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/Pictures/Screenshots"
    state: directory
    mode: "0755"

- name: Configure screenshot location
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_facts['env']['HOME'] }}/Pictures/Screenshots"
    check_type: false
  notify: Restart SystemUIServer

- name: Disable floating screenshot thumbnail preview
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: show-thumbnail
    type: bool
    value: false
    check_type: false
  notify: Restart SystemUIServer

- name: Set screenshot format to PNG
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
    check_type: false
  notify: Restart SystemUIServer

- name: Remove timestamp from screenshot filenames
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: include-date
    type: bool
    value: false
    check_type: false
  notify: Restart SystemUIServer
