---
- name: Change dock preferences
  community.general.osx_defaults:
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    check_type: false
  loop:
    - { key: autohide, type: bool, value: true }
    - { key: show-recents, type: bool, value: false }
    - { key: tilesize, type: int, value: 36 }
    - { key: orientation, type: string, value: left }
  loop_control:
    label: "{{ item.key }}"

- name: Install dockutil
  community.general.homebrew:
    name:
      - dockutil
    state: latest

- name: Clean up dock
  ansible.builtin.include_tasks: remove.yml

- name: Ensure required dock items exist
  ansible.builtin.include_tasks: add.yml
  loop: "{{ dock_items_persist }}"
  loop_control:
    loop_var: dock_item_add
    extended: true
    extended_allitems: false

- name: Ensure dock items are in correct position
  ansible.builtin.include_tasks: position.yml
  loop: "{{ dock_items_persist }}"
  loop_control:
    loop_var: dock_item_position
    extended: true
    extended_allitems: false
  when:
    - dock_item_position.pos is defined
    - dock_item_position.pos > 0

- name: Force dock restart and flush cache
  ansible.builtin.command: killall Dock
  changed_when: false
