- name: Check for Python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: Install Python
  raw: sudo apt-get -y install python3-pip
  when: check_python.rc != 0
