- name: Install Kitty
  become: true
  command: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin 
  # get_url:
  #   url: https://sh.rustup.rs
  #   dest: /tmp/sh.rustup.rs
  #   mode: '0755'
  #   force: 'yes'
