- name: Fetch Kitty Installer
  get_url:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    dest: /tmp/kitty_installer.sh
    mode: '0755'
    force: 'yes'

- name: Install Kitty
  command: /tmp/kitty_installer.sh

- name: Post Install Setup
  command: ~/.dotfiles/scripts/kitty_post_install.sh
