- name: Fetch Noevim Installer
  warn: false
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.deb
    dest: /tmp/nvim-linux64.deb
    mode: '0755'
    force: 'yes'
  tags:
    - Noevim

- name: Install Neovim
  command: apt-get install /tmp/nvim-linux64.deb
  tags:
    - Noevim
