- name: Download OhMyZsh Installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'
    force: 'yes'
  tags:
    - ohmyzsh
  when: lookup('env', "ZSH") == ''

- name: Install OhMyZsh
  command: /tmp/ohmyzsh_install.sh
  when: lookup('env', "ZSH") == ''
