- name: Download OhMyZsh Installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'
    force: 'yes'
  tags:
    - ohmyzsh
  register: ohmyzshl_install

- name: Install OhMyZsh
  command: bash '[ "$ZSH" == "\n" ] && /tmp/ohmyzsh_install.sh'
  when: ohmyzsh_install|success
