- name: Check Installation
  become_user: "{{ ansible_env.SUDO_USER }}"
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_file

- name: Download OhMyZsh Installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'
    force: 'yes'
  tags:
    - ohmyzsh
  when: not ohmyzsh_file.stat.exists

- name: Install OhMyZsh
  become_user: "{{ ansible_env.SUDO_USER }}"
  command: /tmp/ohmyzsh_install.sh
  when: not ohmyzsh_file.stat.exists

- name: Change Shell
  command: zsh

- name: Change Default Shell
  become_user: "{{ ansible_env.SUDO_USER }}"
  shell: 'chsh $USER -s $(which zsh)'
