- name: Check Installation
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_file

- name: Download OhMyZsh Installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'
    force: 'yes'
  tags:
    - ohmyzsh
  when: not ohmyzsh_file.stat.exists

- name: Install OhMyZsh
  command: /tmp/ohmyzsh_install.sh
  when: not ohmyzsh_file.stat.exists

# - name: Change Default Shell
#   command: "chsh -s $(which zsh)"
#   when: not ohmyzsh_file.stat.exists
