---
- name: Show all filename extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify: Restart Finder

- name: Show hidden files
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: Restart Finder

- name: Disable extension change warning
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify: Restart Finder

- name: Show path bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify: Restart Finder

- name: Show status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  notify: Restart Finder

- name: Set default Finder view to list view
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
  notify: Restart Finder

- name: Open new Finder windows in home directory
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfHm
  notify: Restart Finder

- name: Set Finder home directory path
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://{{ ansible_facts['env']['HOME'] }}/"
  notify: Restart Finder

- name: Keep folders on top in list view
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  notify: Restart Finder

- name: Set Finder search scope to current folder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
  notify: Restart Finder

- name: Disable .DS_Store on network drives
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  notify: Restart Finder

- name: Disable .DS_Store on USB drives
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
  notify: Restart Finder

- name: Hide desktop icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
  notify: Restart Finder
