---
- name: update and upgrade packages
  become: true
  apt:
    update_cache: true
    upgrade: dist

- name: install flatpak
  become: true
  apt:
    name:
      - flatpak
    state: latest

- name: add flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install flatpak packages
  include_tasks: install.yml
  loop:
    - com.brave.Browser
    - com.slack.Slack
    - com.spotify.Client
    - com.discordapp.Discord
    - md.obsidian.Obsidian
    - com.getpostman.Postman
    - com.obsproject.Studio
    - com.bitwarden.desktop
    - com.dropbox.Client
    - io.dbeaver.DBeaverCommunity
    - com.google.Chrome
  loop_control:
    loop_var: flatpak_package

- name: update flatpaks
  command: flatpak update
  changed_when: false
