---
- name: install zsh
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - zsh
    state: latest

- name: create .workrc.zsh file
  copy:
    content: "#!/bin/bash"
    dest: "{{ ansible_env.HOME }}/.workrc.zsh"
    force: false
    mode: "0700"
    owner: "{{ ansible_env.USER }}"

- name: set user to change shell
  set_fact:
    zsh_user: "{{ ansible_env.USER }}"

- name: change default shell
  become: true
  shell: "chsh -s $(which zsh) {{ zsh_user }}"
  changed_when: false

- name: create .zshrc symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/zsh/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: true
    follow: false
