---
- name: install required packages
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: latest
  changed_when: false

- name: create /etc/apt/keyrings directory if it doesn't exist
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root

- name: download kubernetes armored GPG key
  become: true
  get_url:
    url: "{{ kubernetes_key_url }}/Release.key"
    dest: "{{ kubernetes_keyring_path }}_armored"

- name: de-armor kubernetes GPG key
  become: true
  shell: "gpg --dearmor < {{ kubernetes_keyring_path }}_armored > {{ kubernetes_keyring_path }}"
  no_log: true
  args:
    executable: /bin/bash
    creates: "{{ kubernetes_keyring_path }}"

- name: add kubernetes repository
  become: true
  apt_repository:
    repo: "deb [signed-by={{ kubernetes_keyring_path }}] {{ kubernetes_key_url }}/ /"
    filename: /etc/apt/sources.list.d/kubernetes

- name: install kubectl
  become: true
  apt:
    name: kubectl
    state: latest

- name: set permissions on kubernetes sources list
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    mode: "0644"
    owner: root
    group: root
