---
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  ansible_args:
    - --connection=local
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
dependency:
  name: galaxy
verifier:
  name: ansible
# test_sequence:
#   - dependency
#   - syntax
#   - converge
#   - idempotence
#   - verify
