---
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  ansible:
    options:
      # previously ansible_args
      connection: local
    env:
      # previously env
      ANSIBLE_ROLES_PATH: "../../roles"
  # ansible_args:
  #   - --connection=local
  # env:
  #   ANSIBLE_ROLES_PATH: "../../roles"
dependency:
  name: galaxy
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
    - idempotence
    - verify
