---
driver:
  name: default
platforms:
  - name: instance
ansible:
  executor:
    args:
      ansible_playbook:
        - --connection=local
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_FORCE_COLOR: "1"
provisioner:
  name: ansible
dependency:
  name: galaxy
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
    - idempotence
    - verify
