---
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: ubuntu
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: macos
    image: "sickcodes/docker-osx:latest"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
