---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include verification tasks for {{ lookup('env', 'MOLECULE_ROLE') }}"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_ROLE') }}"
        tasks_from: "../verify/main.yml"
