---
- name: install git
  become: true
  apt:
    name:
      - git
    state: latest

- name: create .gitconfig symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/git/files/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    state: link
    force: true
    follow: false

- name: create .gitignore_global symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/git/files/.gitignore_global"
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    state: link
    force: true
    follow: false

- name: create .workrc.gitconfig file
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.workrc.gitconfig"
    backup: true
    force: false
    mode: "0700"
    owner: "{{ ansible_env.USER }}"

- name: create work directory
  become: true
  file:
    path: "{{ ansible_env.HOME }}/work/"
    state: directory
    mode: "0755"
    owner: "{{ ansible_env.USER }}"
