# credit: https://stackoverflow.com/questions/51933636/url-for-latest-stable-go-release

- name: check if go is installed
  shell: go --version
  register: go_exists
  ignore_errors: yes


- name: get kernel version
  command: 'uname'
  register: uname_result

- name: Download Installer
  when: go_exists is failed
  get_url:
    url: https://get.golang.org/{{ uname_result.stdout }}/go_installer
    dest: /tmp/go_installer
    mode: '0755'
    force: 'yes'
  tags:
    - go

- name: Install Go
  when: go_exists is failed
  command: /tmp/go_installer
  tags:
    - go
