# credit: https://stackoverflow.com/questions/51933636/url-for-latest-stable-go-release

- name: check if cargo is installed
  shell: command -v cargo
  register: go_exists
  ignore_errors: yes

- name: Download Installer
  when: go_exists is failed
  get_url:
    url: https://get.golang.org/$(uname)/go_installer
    dest: /tmp/go_installer
    mode: '0755'
    force: 'yes'
  tags:
    - go

- name: Install Go
  when: go_exists is failed
  shell: /tmp/go_installer
  tags:
    - go
