local opt = vim.opt
local wo = vim.wo
local g = vim.g
opt.number = true
opt.expandtab = true
opt.smartindent = true
opt.hlsearch = false
opt.hidden = true
opt.wrap = false
opt.incsearch = true
opt.termguicolors = true
opt.cursorline = true
opt.scrolloff = 8
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.cmdheight = 2
opt.guicursor = ''
wo.signcolumn = 'yes'
opt.colorcolumn = '100'
g.mapleader = ' '
