config-version                                                  = 2
after-startup-command                                           = [
  'exec-and-forget /bin/bash -c "PATH=/opt/homebrew/bin:/usr/local/bin:$PATH sketchybar"',
  'exec-and-forget /bin/bash -c "PATH=/opt/homebrew/bin:/usr/local/bin:$PATH borders"',
]
start-at-login                                                  = true
enable-normalization-flatten-containers                         = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding                                               = 0
default-root-container-layout                                   = "tiles"
default-root-container-orientation                              = "auto"
on-focused-monitor-changed                                      = [
  "move-mouse monitor-lazy-center"
]
automatically-unhide-macos-hidden-apps                          = false
exec-on-workspace-change                                        = [
  "/bin/bash",
  "-c",
  "PATH=/opt/homebrew/bin:/usr/local/bin:$PATH sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"
]
persistent-workspaces                                           = [
  "1",
  "2",
  "3",
  "4",
  "q",
  "w",
  "e",
]

[[on-window-detected]]
  if.window-title-regex-substring = "(?i)copying|moving|deleting|alert|save|open|upload|export"
  check-further-callbacks         = true
  run                             = "layout floating"

[[on-window-detected]]
  if.app-id = "com.apple.archiveutility"
  run       = "layout floating"

[[on-window-detected]]
  if.app-id = "com.github.wez.wezterm"
  run       = "move-node-to-workspace 1"

[[on-window-detected]]
  if.app-id = "com.google.Chrome"
  run       = "move-node-to-workspace 2"

[[on-window-detected]]
  if.app-id = "com.tinyspeck.slackmacgap"
  run       = "move-node-to-workspace 3"

[[on-window-detected]]
  if.app-id = "com.postmanlabs.mac"
  run       = "move-node-to-workspace 4"

[[on-window-detected]]
  if.app-id = "notion.id"
  run       = "move-node-to-workspace q"

[[on-window-detected]]
  if.app-id = "com.bitwarden.desktop"
  run       = "move-node-to-workspace w"

[[on-window-detected]]
  if.app-id = "com.apple.finder"
  run       = "layout floating"

[[on-window-detected]]
  if.app-id = "com.apple.ActivityMonitor"
  run       = "layout floating"

[[on-window-detected]]
  if.app-id = "com.apple.systempreferences"
  run       = "layout floating"

[workspace-to-monitor-force-assignment]
  1 = "main"
  2 = "secondary"
  3 = "secondary"
  4 = "secondary"
  q = "secondary"
  w = "main"
  e = "main"

[key-mapping]
  preset = "qwerty"

[gaps]
  inner.horizontal = 10
  inner.vertical   = 10
  outer.left       = 10
  outer.bottom     = 10
  outer.top        = [{ monitor.main = 50 }, 50]
  outer.right      = 10

[mode.main.binding]
  alt-slash   = "layout tiles horizontal vertical"
  alt-h       = "focus left"
  alt-j       = "focus down"
  alt-k       = "focus up"
  alt-l       = "focus right"
  alt-shift-h = "move left"
  alt-shift-j = "move down"
  alt-shift-k = "move up"
  alt-shift-l = "move right"
  alt-minus   = "resize smart -50"
  alt-equal   = "resize smart +50"
  alt-1       = "workspace 1"
  alt-2       = "workspace 2"
  alt-3       = "workspace 3"
  alt-4       = "workspace 4"
  alt-q       = "workspace q"
  alt-w       = "workspace w"
  alt-e       = "workspace e"
  alt-6       = "workspace-back-and-forth"
  alt-shift-1 = "move-node-to-workspace 1"
  alt-shift-2 = "move-node-to-workspace 2"
  alt-shift-3 = "move-node-to-workspace 3"
  alt-shift-4 = "move-node-to-workspace 4"
  alt-shift-q = "move-node-to-workspace q"
  alt-shift-w = "move-node-to-workspace w"
  alt-shift-e = "move-node-to-workspace e"
  alt-i       = "mode service"

[mode.service.binding]
  esc       = ["mode main"]
  r         = ["reload-config", "mode main"]
  f         = ["layout floating tiling", "mode main"]
  backspace = ["close-all-windows-but-current", "mode main"]
  alt-1     = ["exec-and-forget open -a /Applications/Wezterm.app", "mode main"]
  alt-2     = ["exec-and-forget open -a /Applications/Vivaldi.app", "mode main"]
  alt-3     = ["exec-and-forget open -a /Applications/Slack.app", "mode main"]
  alt-4     = ["exec-and-forget open -a /Applications/Postman.app", "mode main"]
  alt-q     = ["exec-and-forget open -a /Applications/Notion.app", "mode main"]
  alt-w     = [
    "exec-and-forget open -a /Applications/Bitwarden.app",
    "mode main"
  ]
  alt-e     = [
    "exec-and-forget open -a /Applications/WhatsApp.app",
    "mode main"
  ]
  alt-d     = ["exec-and-forget open -a /Applications/Discord.app", "mode main"]
  alt-s     = [
    "exec-and-forget open -a '/System/Applications/System Settings.app'",
    "mode main"
  ]
  alt-a     = ["exec-and-forget open -a 'Activity Monitor.app'", "mode main"]
