- name: add ansible user
  user:
    name: ansible-manager
    system: yes

- name: set up sudo for ansible user
  copy:
    src: ansible/cron/su_ansible-manager
    dest: /etc/sudoers.d/ansible-manager
    owner: root
    group: root
    mode: 0440

- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: ansible-manager
    minute: "*/10"
    # run tasks on repo change
    job: ansible-pull -o -U https://github.com/Drew138/.dotfiles.git ansible/local.yml
