---
- name: Enable tap to click (user domain)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

- name: Enable tap to click (trackpad driver)
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: bool
    value: true
    check_type: false
