---
- name: Change keyboard repeat rates
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    - { key: InitialKeyRepeat, type: int, value: 15 }
    - { key: KeyRepeat, type: int, value: 2 }
    - { key: ApplePressAndHoldEnabled, type: bool, value: false }
  loop_control:
    label: "{{ item.key }}"
