---
- name: Ensure FelixKratz Homebrew tap is available
  community.general.homebrew_tap:
    name: FelixKratz/formulae
    state: present

- name: Install sketchybar
  community.general.homebrew:
    name:
      - sketchybar
      - lua
    state: latest

- name: Check whether SbarLua is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/sketchybar_lua/sketchybar.so"
  register: sketchybar_lua_stat

- name: Install SbarLua
  when: not sketchybar_lua_stat.stat.exists
  block:
    - name: Clone SbarLua
      ansible.builtin.git:
        repo: https://github.com/FelixKratz/SbarLua.git
        dest: /tmp/SbarLua
        clone: true
        force: true
        depth: 1

    - name: Build and install SbarLua
      ansible.builtin.command: make install
      args:
        chdir: /tmp/SbarLua
      changed_when: true

    - name: Remove SbarLua build directory
      ansible.builtin.file:
        path: /tmp/SbarLua
        state: absent

- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config"
    state: directory
    mode: "0755"

- name: Create sketchybar symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/sketchybar/files"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/sketchybar"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
