// Watches the pasteboard and keeps the last few entries for the bar's clipboard widget.
//
// macOS has no clipboard-changed notification, so the only way is to poll the change
// counter, which is cheap. What it refuses to store matters more than what it stores: this
// machine handles card data and provider credentials, and a history file outlives whatever
// was copied into it.
import AppKit
import Foundation

let maximumEntries = 15
let pollSeconds = 0.7
let storePath = NSString(string: "~/.cache/sketchybar/clipboard.tsv").expandingTildeInPath
let sketchybar = "/opt/homebrew/bin/sketchybar"

// Apps mark a copy as concealed (password managers), transient or auto-generated. All three
// are things the user never asked to keep.
let ignoredTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
]

let secretPatterns = [
    "-----BEGIN [A-Z ]*PRIVATE KEY-----",
    "arn:aws:secretsmanager",
    "\\b(?:\\d[ -]?){12,18}\\d\\b",        // card-shaped
    "(?i)(password|passwd|secret|token|api[_-]?key)\\s*[:=]",
]

func looksSensitive(_ text: String) -> Bool {
    for pattern in secretPatterns {
        if text.range(of: pattern, options: .regularExpression) != nil {
            return true
        }
    }
    return false
}

func escape(_ text: String) -> String {
    text.replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\n", with: "\\n")
        .replacingOccurrences(of: "\r", with: "")
        .replacingOccurrences(of: "\t", with: "\\t")
}

func load() -> [String] {
    guard let contents = try? String(contentsOfFile: storePath, encoding: .utf8) else {
        return []
    }
    return contents.split(separator: "\n", omittingEmptySubsequences: true).map(String.init)
}

func save(_ entries: [String]) {
    let directory = (storePath as NSString).deletingLastPathComponent
    try? FileManager.default.createDirectory(atPath: directory, withIntermediateDirectories: true)

    let body = entries.prefix(maximumEntries).joined(separator: "\n") + "\n"
    try? body.write(toFile: storePath, atomically: true, encoding: .utf8)

    // Readable only by this user: it is a log of everything copied.
    try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: storePath)
}

func notifyBar() {
    let task = Process()
    task.executableURL = URL(fileURLWithPath: sketchybar)
    task.arguments = ["--trigger", "clipboard_update"]
    try? task.run()
}

// Only one watcher should ever run. It takes an exclusive lock rather than having the
// caller pkill by name: that pattern also matches the shell doing the killing.
let lockPath = NSString(string: "~/.cache/sketchybar/clipwatch.lock").expandingTildeInPath
try? FileManager.default.createDirectory(
    atPath: (lockPath as NSString).deletingLastPathComponent,
    withIntermediateDirectories: true
)

let lockDescriptor = open(lockPath, O_CREAT | O_RDWR, 0o600)

if lockDescriptor < 0 || flock(lockDescriptor, LOCK_EX | LOCK_NB) != 0 {
    exit(0)
}

let pasteboard = NSPasteboard.general
var lastChangeCount = pasteboard.changeCount

while true {
    if pasteboard.changeCount != lastChangeCount {
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map { $0.rawValue })
        let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines)

        if let text, !text.isEmpty, types.isDisjoint(with: ignoredTypes), !looksSensitive(text) {
            var entries = load()
            let line = escape(text)

            entries.removeAll { $0 == line }
            entries.insert(line, at: 0)

            save(entries)
            notifyBar()
        }
    }

    Thread.sleep(forTimeInterval: pollSeconds)
}
