require('plug-config')
require('extensions.coc')
require('extensions.comment')
require('extensions.gitgutter')
require('extensions.nightfox')
require('extensions.telescope')
require('extensions.treesitter')
require('extensions.nerdtree')