---
- name: Disable system error beep
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.sound.beep.feedback
    type: bool
    value: false

- name: Mute startup chime
  ansible.builtin.command: >
    nvram StartupMute=%01
  become: true
  changed_when: false
