- name: Download Algorithms Repository
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: 'git@github.com:Drew138/algorithms.git'
    dest: "~/dev/algorithms"
    clone: yes
    update: yes

- name: Download Competitive Programming Repository
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: 'git@github.com:Drew138/competitive-programming.git'
    dest:  "~/dev/competitive-programming"
    clone: yes
    update: yes

- name: Download Graphics-App Repository
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: 'git@github.com:Drew138/graphics-app.git'
    dest: "~/dev/graphics-app"
    clone: yes
    update: yes

- name: Download Dotfiles Repository
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: git@github.com:Drew138/.dotfiles.git
    dest: "~/.dotfiles"
    clone: yes
    update: yes
