---
name: ci

"on":
  push:
    paths-ignore:
      - "**.md"
      - "assets/**"
      - "LICENSE"
  schedule:
    - cron: "0 7 * * 0"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@v6

      - name: set up python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: lint code
        run: |
          yamllint .
          ansible-lint ./*

  check-roles:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      roles: ${{ steps.roles.outputs.roles }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: install jq
        run: sudo apt-get install jq

      - name: list ansible roles
        id: roles
        run: |
          echo 'roles<<EOF' >> "${GITHUB_OUTPUT}"
          roles=$(ls -1 -d */ | sed 's:/$::' | jq -R -s 'split("\n")[:-1]')
          echo $roles>> "${GITHUB_OUTPUT}"
          echo 'EOF' >> "${GITHUB_OUTPUT}"
        working-directory: ./roles/

  test-macos:
    needs: check-roles
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        role: ${{ fromJson(needs.check-roles.outputs.roles) }}
    steps:
      - name: check out the codebase
        uses: actions/checkout@v6

      - name: set up python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: uninstall various programs
        run: |
          rm -rf /usr/local/go
          rm -rf ~/go
          rm -rf ~/.cargo
          rm -rf ~/.nvm
          rm -rf ~/go
          rm -rf ~/.go
          sudo rm -rf /opt/homebrew/bin/cpack
          sudo rm -rf /opt/homebrew/bin/ctest
          sudo rm -rf /opt/homebrew/bin/ccmake
          sudo rm -rf /opt/homebrew/bin/cmake

      - name: refresh homebrew metadata
        env:
          ROLE: ${{ matrix.role }}
        run: |
          if grep -rq "community.general.homebrew" "roles/${ROLE}"; then
            brew update
          else
            echo "roles/${ROLE} does not use homebrew, skipping the refresh"
          fi

      - name: install test dependencies
        run: pip3 install \
          ansible \
          molecule

      - name: create password file
        run: echo "${ANSIBLE_VAULT_PASSWORD}" > ./molecule/default/vaultpassword
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: run molecule tests
        run: molecule test
        env:
          ROOT_DIR: ${{ github.workspace }}
          PY_COLORS: "1"
          ANSIBLE_VAULT_PASSWORD_FILE: ./vaultpassword
          MOLECULE_ROLE: ${{ matrix.role }}
          GHUB_ACCESS_TOKEN: ${{ secrets.GHUB_ACCESS_TOKEN }}

  notify-errors:
    needs: test-macos
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'schedule'
    steps:
      - name: send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Dotfiles Error
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}
          body: dotfiles test failed, check needed
